language: elixir
elixir: '1.4.5'
otp_release: '20.0'
cache:
  directories:
    - deps
before_install:
  - cp config/dev.exs.example config/dev.exs
  - cp config/test.exs.example config/test.exs
script: mix test
